import { ChevronDown, LogOut, Plus, Settings, Ticket, Users } from "lucide-react";
import { Card, CardContent, CardHeader } from "../../components/ui/card";
import { useAuth } from "../auth/AuthContext";
import { Link } from "react-router-dom";
import { ProjectsWorkspace } from "../projects/ProjectsWorkspace";
import { Avatar, AvatarFallback } from "../../components/ui/avatar";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "../../components/ui/dropdown-menu";

function roleInitials(role?: string) { return role === "APP_ADMIN" ? "AA" : role === "CLIENT_ADMIN" ? "CA" : "CU"; }

export function DashboardPage() { const { user, logout } = useAuth(); return <div className="min-h-screen"><header className="border-b bg-card"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Pridesys</p><h1 className="text-lg font-semibold">Ticketing workspace</h1></div><DropdownMenu><DropdownMenuTrigger asChild><button type="button" aria-label="Open account menu" className="group flex items-center gap-2 rounded-full p-1.5 outline-none transition hover:bg-muted focus-visible:ring-2 focus-visible:ring-ring"><Avatar className="h-10 w-10 shadow-sm"><AvatarFallback>{roleInitials(user?.role)}</AvatarFallback></Avatar><ChevronDown className="h-4 w-4 text-muted-foreground transition group-data-[state=open]:rotate-180" /></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel><p className="font-semibold text-foreground">{user?.name}</p><p className="mt-1 font-normal text-muted-foreground">{user?.email}</p><span className="mt-2 inline-flex rounded-full bg-accent px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-accent-foreground">{user?.role.replace("_", " ")}</span></DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuItem asChild><Link to="/profile"><Settings className="mr-2 h-4 w-4" />Profile settings</Link></DropdownMenuItem><DropdownMenuItem onSelect={logout} className="text-red-700 focus:bg-red-50 focus:text-red-700"><LogOut className="mr-2 h-4 w-4" />Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header><main className="mx-auto max-w-7xl space-y-8 px-6 py-10"><div><p className="text-sm text-muted-foreground">Good to see you again</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">Your workspace</h2></div><div className="grid gap-5 md:grid-cols-3"><Card><CardHeader><Ticket className="h-5 w-5 text-primary" /><p className="text-sm text-muted-foreground">Open issues</p></CardHeader><CardContent><p className="text-3xl font-semibold">—</p><p className="mt-1 text-xs text-muted-foreground">Issue board arrives in the next increment</p></CardContent></Card><Card><CardHeader><Users className="h-5 w-5 text-primary" /><p className="text-sm text-muted-foreground">Projects</p></CardHeader><CardContent><p className="text-3xl font-semibold">—</p><p className="mt-1 text-xs text-muted-foreground">Connected to the Spring API foundation</p></CardContent></Card><Card><CardHeader><Plus className="h-5 w-5 text-primary" /><p className="text-sm text-muted-foreground">Next action</p></CardHeader><CardContent><p className="text-sm font-medium">Create your first issue</p><p className="mt-1 text-xs text-muted-foreground">Available when the issue workflow is added</p></CardContent></Card></div><ProjectsWorkspace /></main></div>; }
