import { useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardHeader } from "../../components/ui/card";
import { Input } from "../../components/ui/input";
import { useAuth } from "./AuthContext";

export function ProfilePage() {
  const { user, updateProfile, changePassword } = useAuth();
  const [profile, setProfile] = useState({ name: user?.name ?? "", mobile: user?.mobile ?? "", designation: user?.designation ?? "", office: user?.office ?? "" });
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function saveProfile(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); try { await updateProfile(profile); setMessage("Profile updated successfully."); } catch (exception) { setError(exception instanceof Error ? exception.message : "Unable to update profile"); } finally { setSaving(false); } }
  async function savePassword(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); try { await changePassword(currentPassword, newPassword); setCurrentPassword(""); setNewPassword(""); setMessage("Password changed successfully."); } catch (exception) { setError(exception instanceof Error ? exception.message : "Unable to change password"); } finally { setSaving(false); } }
  return <main className="min-h-screen bg-background px-4 py-8"><div className="mx-auto max-w-3xl space-y-6"><Link to="/" className="text-sm font-medium text-primary hover:underline">← Back to workspace</Link><div><p className="text-sm text-muted-foreground">Account settings</p><h1 className="text-3xl font-semibold tracking-tight">Your profile</h1></div>{(message || error) && <p role="alert" className={error ? "rounded-lg bg-red-50 p-3 text-sm text-red-700" : "rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700"}>{error || message}</p>}<Card><CardHeader><h2 className="text-xl font-semibold">Personal information</h2><p className="text-sm text-muted-foreground">Keep your contact details up to date.</p></CardHeader><CardContent><form onSubmit={saveProfile} className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-sm font-medium">Email<Input value={user?.email ?? ""} disabled /></label><label className="space-y-2 text-sm font-medium">Name<Input required value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} /></label><label className="space-y-2 text-sm font-medium">Mobile<Input value={profile.mobile} onChange={(e) => setProfile({ ...profile, mobile: e.target.value })} /></label><label className="space-y-2 text-sm font-medium">Designation<Input value={profile.designation} onChange={(e) => setProfile({ ...profile, designation: e.target.value })} /></label><label className="space-y-2 text-sm font-medium sm:col-span-2">Office<Input value={profile.office} onChange={(e) => setProfile({ ...profile, office: e.target.value })} /></label><Button disabled={saving} className="sm:col-span-2">Save profile</Button></form></CardContent></Card><Card><CardHeader><h2 className="text-xl font-semibold">Change password</h2><p className="text-sm text-muted-foreground">Use at least eight characters.</p></CardHeader><CardContent><form onSubmit={savePassword} className="space-y-4"><label className="block space-y-2 text-sm font-medium">Current password<Input required type="password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} /></label><label className="block space-y-2 text-sm font-medium">New password<Input required minLength={8} type="password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} /></label><Button disabled={saving}>Change password</Button></form></CardContent></Card></div></main>;
}
